[숫자야구] 권순찬 미션 제출합니다.
econo-spring-2021/java-baseball pull request #1
Opened 2021-04-14 03:37 UTC by Kwon770

2021-04-15 08:21 UTC, hotheadfactory requested changes
안녕하세요 순찬님! 잘 구현해 주셨습니다:)
알고리즘 킹답게 캐시를 이용하신 것도 인상 깊었고요.
몇 가지만 고치면 될 것 같습니다!! 수정 사항 반영 후에 다시 머지요청 해 주세요.

2021-04-15 08:21 UTC, hotheadfactory commented on src/main/java/baseballGame/Main.java
> +class BallAvailbilty {
.java 파일 하나에 여러 개의 클래스를 만들 수는 있으나 한 개만 public으로 선언할 수 있고, 경우에 따라 문제를 일으킬 수 있으므로 탑 레벨 클래스는 한 파일에 한 개만 담는 것이 좋습니다.
참고: https://songiam.tistory.com/62

2021-04-15 08:21 UTC, hotheadfactory commented on src/main/java/baseballGame/Main.java
> +    public static int returnStrikeCntAndMakeBallCache(int[] computerBall, int[] playerBall, int[] ballCache) {
메소드 명에 And가 들어간다는 것은 하나의 메소드가 두 가지 이상의 일을 한번에 하고 있다는 신호입니다.
> 함수(또는 메소드)가 한 가지 일만 하도록 최대한 작게 만들어라.

2021-04-15 08:21 UTC, hotheadfactory commented on src/main/java/baseballGame/Main.java
> +            ball[i] = (int) (Math.random() * 10);
> 이 게임은 기본적으로 1부터 9까지 서로 다른 수로 이루어진 3자리의 수를 맞추는 게임이다. 

0이 등장하고 중복된 숫자가 나오는 부분에 대해서 예외 처리가 필요해 보입니다!

2021-04-27 02:55 UTC, Kwon770 commented
@hotheadfactory 피드백해주신 부분 잘 읽어 보았습니다! 그에맞게 리펙토링하였습니다.

> 메소드 명에 And가 들어간다는 것은 하나의 메소드가 두 가지 이상의 일을 한번에 하고 있다는 신호입니다.

이 부분은 늘 제가 고민하는 부분인데, 메소드가 하나의 일을 하도록 모두 나누게 되면 불필요한 매개변수 전달과 반복의 과정이 생기는 경우가 많다고 느끼고 있습니다. 이는 가독성을 위해 감수해야하는 부분일까요? 아니면 더 효율적으로 짜면 해결할 수 있는 문제일까요?

2021-04-28 15:11 UTC, hotheadfactory commented
후자에 가깝다고 할 수 있습니다. 객체 지향적으로 잘 설계된 도메인 모델에서 메소드를 호출해 사용한다면, 꼭 필요한 파라미터만 전달하면 됨은 물론 해당 메소드가 정확히 무슨 일을 하는지도 코드를 통해 직관적이고 쉽게 유추할 수 있게 됩니다.
**일반적으로 한 메소드가 한 가지 일만, 15줄 또는 10줄을 넘지 않도록 노력하라는 말을 많이 하는데, 그렇다고 해서 이걸 IntelliJ의 메소드 추출 기능 등으로 억지로 분리하면 오히려 비 직관적이고 불필요한 매개 변수를 전달하는 메소드가 될 수도 있습니다.**
좋은 설계가 선행되어야 한 번에 한 가지 일만 하는 간결한 메소드도 자연스럽게 만들 수 있게 되는 것이지요. 이 부분에 대해서는 이번 미션 피드백과 다음 미션 설명하는 시간에 설명하겠습니다.

2021-05-07 10:53 UTC, hotheadfactory approved these changes

2021-05-12 08:55 UTC, merged