[숫자야구] 김송아 미션 제출합니다.
econo-spring-2021/java-baseball pull request #2
Opened 2021-04-14 12:25 UTC by asong57

2021-04-15 08:27 UTC, hotheadfactory requested changes
안녕하세요 송아님 :) 
요구사항에 맞게 잘 구현해 주셨습니다!
딱 한 가지만 수정해 주시면!! 바로 Approve 해 드릴게요!

2021-04-15 08:27 UTC, hotheadfactory commented on src/main/java/Main.java
> +            answer[i] = (int) (Math.random() * 10);
> 이 게임은 기본적으로 1부터 9까지 서로 다른 수로 이루어진 3자리의 수를 맞추는 게임이다.

0이 등장하고 중복된 숫자가 나오는 부분에 대해서 예외 처리가 필요해 보입니다!

2021-04-16 07:38 UTC, asong57 commented on src/main/java/Main.java
> +            answer[i] = (int) (Math.random() * 10);
아차차 넵 알겠습니다!

2021-04-26 14:15 UTC, hotheadfactory approved these changes

2021-05-12 08:55 UTC, merged