탁민경 제출
econo-spring-2021/java-baseball pull request #3
Opened 2021-04-14 17:45 UTC by mtak0235

2021-04-15 09:45 UTC, hotheadfactory requested changes
안녕하세요 민경님:) 잘 구현해주셨어요!
클래스를 나누는 시도를 해 주셨는데요, 아주 좋습니다 :)
이 부분에 대해서는 2주차 미션에서 더 자세히 다룰 예정입니다!
피드백 확인하시고 수정 후 다시 리뷰요청 해 주세요!

2021-04-15 09:45 UTC, hotheadfactory commented on src/main/java/baseball/Application.java
> +                    break;
> indent(인덴트, 들여쓰기) depth를 3이 넘지 않도록 구현한다. 2까지만 허용한다.
> 예를 들어 while문 안에 if문이 있으면 들여쓰기는 2이다.
> 힌트: indent(인덴트, 들여쓰기) depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 된다. 

인덴트가 3을 넘었습니다. 리팩토링 해 주세요!

2021-04-15 13:22 UTC, mtak0235 commented on src/main/java/baseball/Application.java
> +                    break;
으아닛 넵!

2021-04-26 14:15 UTC, hotheadfactory approved these changes

2021-05-12 08:55 UTC, merged