[숫자야구] 홍동건 미션 제출합니다.
econo-spring-2021/java-baseball pull request #4
Opened 2021-04-14 19:02 UTC by Hongdonggeon

2021-04-26 07:28 UTC, hotheadfactory requested changes
안녕하세요 동건님!!
요구사항에 맞게 잘 구현해 주셨어요!
간단한 피드백 남겼으니 확인해 주세요~!

2021-04-26 07:28 UTC, hotheadfactory commented on src/main/java/Main.java
> +       if(ball_flag && ball_cnt<=0 && strike_cnt<3){
play() 메소드가 상당히 긴 것 같은데요,
출력 부분 로직을 메소드 분리하는 것을 고려해볼 만한 것 같습니다!

2021-04-26 07:28 UTC, hotheadfactory commented on src/main/java/Main.java
> +    static void strike_count (int[] user){
메소드의 이름은 명사보다는 동사로 하는 것이 좋습니다.
이 메소드가 '무엇을 하는지' 를 정확히 표현할 수 있는 이름을 고민해 보세요!

2021-04-26 07:55 UTC, Hongdonggeon commented on src/main/java/Main.java
> +       if(ball_flag && ball_cnt<=0 && strike_cnt<3){
네 알겠습니다!!

2021-04-26 07:56 UTC, Hongdonggeon commented on src/main/java/Main.java
> +    static void strike_count (int[] user){
넵 피드백 감사합니다!

2021-04-28 14:58 UTC, hotheadfactory approved these changes

2021-05-12 08:56 UTC, merged