[숫자야구] 김정인 과제 제출합니다.
econo-spring-2021/java-baseball pull request #7
Opened 2021-05-07 08:06 UTC by mywnajsldkf

정말 늦어서 정말 죄송합니다 🐢 🐢 
앞으로 시간 엄수하도록 노력하겠습니다.

게임 다시 시작할 때 컴퓨터가 새로운 숫자를 출력하는 부분을 아직 해결하지 못했습니다.
이 부분에서 멘토님의 조언 부탁드립니다 :)

2021-05-07 10:52 UTC, hotheadfactory requested changes
안녕하세요 정인님!!
바쁜 시험기간과 논문제출을 뚫고!! 미션을 완료해 주셔서 감사합니다.
몇 가지 피드백이 있으니 적용해 주세요!

2021-05-07 10:52 UTC, hotheadfactory commented on src/main/java/BaseballGame.java
> +            int computerNumber = createRandom.nextInt(9);
컴퓨터가 생각하는 3자리 숫자는 1부터 9까지의 '서로 다른' 숫자 3개여야 합니다.
이 코드에는 중복된 숫자가 있는 경우(예: 424)에 대한 예외 처리가 없습니다. 예외처리 부탁드립니다!

2021-05-07 10:52 UTC, hotheadfactory commented on src/main/java/BaseballGame.java
> +    static int[] userNumber(int userInput) {
userNumber나 computerNumber나 결국 `1부터 9까지 범위 내의, 서로 다른 3개의 정수`라는 공통된 특징을 가지고 있습니다.
중복된 코드를 줄이고 보다 객체 지향적으로 짤 수 있을까요?

2021-05-07 10:52 UTC, hotheadfactory commented on src/main/java/BaseballGame.java
> +            System.out.println(strikeCount+" 스트라이크" +" , "+ballCount+" 볼");
예시처럼 0스트라이크나 0볼을 굳이 표시하지 않고, `2스트라이크`, `3볼` 식으로 표시할 수 있도록 코딩해 봅시다!
힌트: StringBuilder를 이용해 보세요!

2021-05-12 07:31 UTC, mywnajsldkf commented on src/main/java/BaseballGame.java
> +            int computerNumber = createRandom.nextInt(9);
오!!! 주의하겠습니다

2021-05-12 07:32 UTC, mywnajsldkf commented on src/main/java/BaseballGame.java
> +    static int[] userNumber(int userInput) {
아하! 좀 더 고민해보겠습니다. `1부터 9까지 범위 내의, 서로 다른 3개의 정수` 라는 것을 내뿜는 함수는 만드는거죠...?

2021-05-12 07:32 UTC, mywnajsldkf commented on src/main/java/BaseballGame.java
> +            System.out.println(strikeCount+" 스트라이크" +" , "+ballCount+" 볼");
오... 처음 들어봐요! 감사합니다!

2021-05-12 07:38 UTC, mywnajsldkf commented on src/main/java/BaseballGame.java
> +    static int[] userNumber(int userInput) {
@hotheadfactory 회형님 그런데 userNumber의 경우 사용자가 `111`, `222` 등으로 서로 같은 정수를 입력해도 괜찮지 않나요?

2021-05-12 09:53 UTC, hotheadfactory requested changes

2021-05-12 09:53 UTC, hotheadfactory commented on src/main/java/BaseballGame.java
> +    static int[] userNumber(int userInput) {
@mywnajsldkf 잠결에 보다 보니 좀 헷갈렸었나봐요 @_@ `userNumber`와 `computerNumber`는 클래스가 아닌 유틸리티 메서드였군요! 그러면 상관은 없지만... 현재 이름은 동사 형식의 메소드 이름이 아닌 도메인 클래스/객체를 나타내는 명사형 이름으로 혼동을 줄 가능성이 있으니 한번 바꿔 보아요! `parseUserNumber` 등으로...

2021-05-12 09:53 UTC, hotheadfactory commented on src/main/java/BaseballGame.java
> +                computerNumber();
```
게임 다시 시작할 때 컴퓨터가 새로운 숫자를 출력하는 부분을 아직 해결하지 못했습니다.
이 부분에서 멘토님의 조언 부탁드립니다 :)
```

computerNumber()가 랜덤 3자리 숫자를 생성하여 리턴하는 역할을 합니다. 
9번째 줄에서 보면 처음 실행 시에 computerNumber 변수에 computerNumber()의 실행값을 할당했죠?
하지만 while문 안에서는 computerNumber()를 단순 호출할 뿐, 변수 computerNumber에 새로 만들어진 랜덤 숫자를 재할당하지 않았네요!
또한 23~25줄의 내용은 아래의 패배 분기와 중복되는 것으로 보이는데, 이런 중복을 어떻게 줄일 수 있을지도 고민해 보아요.

2021-07-03 08:17 UTC, mywnajsldkf commented
@hotheadfactory 회형님! 리뷰 반영하였습니다.

2021-07-03 16:33 UTC, hotheadfactory approved these changes
수고하셨습니다 :)

2021-07-08 12:16 UTC, merged